name: hoge CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - uses: actions/checkout@v2
