name: hoge CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: self-hosted
    if: "contains(join(github.event.pull_request.labels.*.name), 'WIP')"
    steps:
    - uses: actions/checkout@v2
